// -----------Roberts-class monitor-HMS Roberts-----------
const calculaMedidaHMSRoberts = (valor) => {
    let r1 = (600*valor)/264;
    let r2 = `${valor} -> ${r1.toFixed(2)} -> ${Math.round(r1)}`;
    return r2;
};
// -------------------------------------------------------
console.log(`C01 -> 264 -> 600 -> 600`);
console.log(`C02 -> ${calculaMedidaHMSRoberts(1)}`);
console.log(`C03 -> ${calculaMedidaHMSRoberts(9.5)}`);
console.log(`C04 -> ${calculaMedidaHMSRoberts(23.5)}`);
console.log(`C05 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C06 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C07 -> ${calculaMedidaHMSRoberts(23.5)}`);
console.log(`C08 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C09 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C10 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C11 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C12 -> ${calculaMedidaHMSRoberts(23.5)}`);
console.log(`C13 -> ${calculaMedidaHMSRoberts(14.5)}`);
console.log(`C14 -> ${calculaMedidaHMSRoberts(8.5)}`);
console.log(`C15 -> ${calculaMedidaHMSRoberts(12)}`);
console.log(`C16 -> ${calculaMedidaHMSRoberts(11)}`);
console.log(`C17 -> ${calculaMedidaHMSRoberts(23)}`);
console.log(`C18 -> ${calculaMedidaHMSRoberts(22.5)}`);
console.log(`C19 -> ${calculaMedidaHMSRoberts(22)}`);
console.log(`C20 -> ${calculaMedidaHMSRoberts(21)}`);
console.log(`C21 -> ${calculaMedidaHMSRoberts(20.5)}`);
console.log(`C22 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C23 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C24 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C25 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C26 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C27 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C28 -> ${calculaMedidaHMSRoberts(20)}`);
console.log(`C29 -> ${calculaMedidaHMSRoberts(17)}`);
console.log(`C30 -> ${calculaMedidaHMSRoberts(14)}`);
console.log(`C31 -> ${calculaMedidaHMSRoberts(9)}`);
console.log(`C32 -> ${calculaMedidaHMSRoberts(5)}`);
console.log(`C33 -> ${calculaMedidaHMSRoberts(3.5)}`);
console.log(`C34 -> ${calculaMedidaHMSRoberts(5)}`);
console.log(`C35 -> ${calculaMedidaHMSRoberts(4.5)}`);
console.log(`C36 -> ${calculaMedidaHMSRoberts(5)}`);
console.log(`C37 -> ${calculaMedidaHMSRoberts(10)}`);
console.log(`C38 -> ${calculaMedidaHMSRoberts(7)}`);
console.log(`C39 -> ${calculaMedidaHMSRoberts(4)}`);
console.log(`C40 -> ${calculaMedidaHMSRoberts(64)}`);
console.log(`C41 -> ${calculaMedidaHMSRoberts(56)}`);
console.log(`C42 -> ${calculaMedidaHMSRoberts(42)}`);
console.log(`C43 -> ${calculaMedidaHMSRoberts(7)}`);
console.log(`C44 -> ${calculaMedidaHMSRoberts(5)}`);
console.log(`C45 -> ${calculaMedidaHMSRoberts(7)}`);
console.log(`C46 -> ${calculaMedidaHMSRoberts(8)}`);
console.log(`C47 -> ${calculaMedidaHMSRoberts(9)}`);
console.log(`C48 -> ${calculaMedidaHMSRoberts(5)}`);
console.log(`C49 -> ${calculaMedidaHMSRoberts(8)}`);
// -------------------------------------------------------